### ISSUE TITLE
Run as a service instead of a simple container

### ISSUE THREAD

**Issue by trajano** [shamil/docker-jenkins-auto-slave#1]
Is it possible to run this as a service rather than a simple container that way it can be used in docker swarm?  If it builds as a container it will build itself only on the node it interacts with rather than a free node.

**Comment by shamil** [comment]
Not sure I understand the problem. What you mean as a service?

**Comment by trajano** [comment]
When starting the container, it runs it on the docker node associated with it.  The problem is that it will only run on that node.  If it was made into a service, it will run it in a swarm and the swarm manager will designate which node it wants to work with and route the network requests appropriately.

**Comment by shamil** [comment]
Sorry, still not sure I get you.

You are the one who decides where and how it runs. This project just gives you a docker image that you can use the way you like. In README I show just as an example how to run the docker image locally, but nothing stops you from running it in any other place be it `docker-swarm`, `kubernetes`, `nomad`, or any other cluster that docker compatiable...

In our environment we run it under `kubernetes` without issues

**Comment by trajano** [comment]
Closing for now, it's been a while since I looked into this and I have already moved on.
