### ISSUE TITLE
Add a possibility to add an agent label 

### ISSUE THREAD

**Issue by itaymelamed** [shamil/docker-jenkins-auto-slave#4]
When creating the slave, it would be nice if I can have the possibility to add labels to the slave. And also change the default behavior to run stage on the slave only when labels are matching.

**Comment by shamil** [comment]
Fixed in https://github.com/shamil/docker-jenkins-auto-slave/commit/7c5546300655761c80b4a7e3448ba22a35ffacfc

Docker image tagged both as `latest` and as as `1.0.0` tags...
